server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-course
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/digitalhouse-dev
    username: usr-digitalhouse
    password: pwd-digitalhouse
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka