AWSTemplateFormatVersion: "2010-09-09"
Description: Automatizamos Bucket S3
Parameters:
 BucketName:
   Type: String
   Description: El bucket de mi Bucket S3
Metadata:
 AWS::CloudFormation::Interface:
   ParametersGroup:
   - Label:
           default: Bucket S3
     Parameters:
     - BucketName
   ParametersLabel:
     BucketName:
       default: 'Nombre de mi Bucket: '
Resources:
 S3Bucket:
   Type: AWS::S3::Bucket
   Properties:
     BucketName: !Ref BucketName
     PublicAccessBlockConfiguration:
       BlockPublicAcls: true
       BlockPublicPolicy: true
       IgnorePublicAcls: true
       RestrictPublicBuckets: true
     VersioningConfiguration: 
       Status: Enabled