INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Jhon', 'courses/Java', 500,'2022-09-25');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Michael', 'courses/Java', 500,'2022-09-28');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Peter', 'courses/Java', 500,'2022-10-05');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Sebastian', 'courses/Java', 500,'2022-10-15');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Aaron', 'courses/Java', 500,'2022-10-25');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'William', 'courses/Java', 500,'2022-10-26');
